apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: podt2-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podt2
  template:
    metadata:
      labels:
        app: podt2
    spec:
      containers:
        - image: iesgn/test_web:latest
          name: cont-web
