apiVersion: apps/v1
kind: Deployment
metadata:
  name: podt3-deployment
  labels:
    app: podt3
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: podt3
  template:
    metadata:
      labels:
        app: podt3
    spec:
      containers:
      - image: iesgn/test_web:latest
        name: cont-web
        ports:
        - name: http
          containerPort: 80
