apiVersion: apps/v1
kind: Deployment
metadata:
  name: podt3-1-deployment
  labels:
    app: podt3-1
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: podt3-1
  template:
    metadata:
      labels:
        app: podt3-1
    spec:
      containers:
      - image: iesgn/test_web:version1
        name: cont-web
        ports:
        - name: http
          containerPort: 80
